version: "1"

services:
  backend:
    container_name: yourMusic-Backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8010:80"
    volumes:
      - ./backend:/var/www/html
    environment:
      - spotify_client_id=f3604350be741a5962c79f36 => ID
      - spotify_client_secret=198d1c1cda4b9099d09306e4 => SECRET
      - spotify_redirect_uri=https://localhost:8010/api/v1/callback.php
      - homepage_url=https://localhost:5173

  frontend:
    container_name: yourMusic-Frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
