version: "1"

services:
  backend_sp:
    container_name: yourMusic-Backend-sp
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/html
    environment:
      - spotify_client_id=YOUR_SECRET_CODE
      - spotify_client_secret=YOUR_SECRET_CODE
      - spotify_redirect_uri=https://spbackend.tensi.dev/api/v1/callback.php
      - homepage_url=https://sp.tensi.dev

  frontend_sp:
    container_name: yourMusic-Frontend-sp
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: https://spbackend.tensi.dev/api/v1
    volumes:
      - ./frontend:/app

    depends_on:
      - backend_sp
networks:
  default:
    external: true
    name: mynetwork
